import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="nav">
          <ul className="nav_elements">
            <Image
              src="/y18.svg"
              alt="Vercel Logo"
              className={"logo"}
              width={20}
              height={20}
              priority
            />
            <li className="hacker_news">Hacker News</li>
            <li>new</li>
            <li>threads</li>
            <li>past</li>
            <li>comments</li>
            <li>ask</li>
            <li>show</li>
            <li>jobs</li>
            <li>submit</li>
          </ul>
          <ul className="name_logout">
            <li>Gbotex</li>
            <li>Logout</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
