import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="container">
            <div className="header-content">
              <div className="logo-title">
                <a href="#" className="logo">
                  <img src="logo.png" alt="Hacker News" />
                </a>
                <a href="#" className="title">
                  Hacker News
                </a>
              </div>
              <nav className="nav-links">
                <a href="#">new</a>
                <a href="#">past</a>
                <a href="#">comments</a>
                <a href="#">ask</a>
                <a href="#">show</a>
                <a href="#">jobs</a>
                <a href="#">submit</a>
              </nav>
              <div className="login">
                <a href="#">login</a>
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
